name: Cargo Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_cli:
    name: Foil CLI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --features buildinfo
  build_backend:
    name: Foil Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
  build_builder:
    name: Foil Builder
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli/builder
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm start
